# Generated by Django 3.2.9 on 2021-12-27 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunch_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lunch',
            name='date',
            field=models.DateField(unique=True, verbose_name='date'),
        ),
    ]
